server:
  port: 8881
spring:  application:    name: druid  mvc:    static-path-pattern: /static/**    view:      prefix: /pages/
      suffix: .jsp  datasource:    url: jdbc:mysql://localhost:3306/zacharychao?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 000000
mybatis:  mapper-locations:  - classpath:mapper/*.xml
  type-aliases-package: com.zacharychao.druid.example.pojo